- name: Provisionar e configurar ambiente TechShop
  hosts: all
  become: yes
  tasks:
    - name: Instalar o Java JDK 21
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Instalar Maven
      apt:
        name: maven
        state: present

    - name: Clonar o repositório da aplicação
      git:
        repo: 'https://github.com/1DanielMarques/techshop.git'
        dest: /opt/techshop
        version: master

    - name: Configurar settings.xml
      shell: |
        mkdir -p ~/.m2
        echo '<?xml version="1.0" encoding="UTF-8"?>' > ~/.m2/settings.xml
        echo '<settings>' >> ~/.m2/settings.xml
        echo '  <mirrors>' >> ~/.m2/settings.xml
        echo '    <mirror>' >> ~/.m2/settings.xml
        echo '      <id>central</id>' >> ~/.m2/settings.xml
        echo '      <mirrorOf>central</mirrorOf>' >> ~/.m2/settings.xml
        echo '      <url>https://repo.maven.apache.org/maven2</url>' >> ~/.m2/settings.xml
        echo '    </mirror>' >> ~/.m2/settings.xml
        echo '  </mirrors>' >> ~/.m2/settings.xml
        echo '</settings>' >> ~/.m2/settings.xml

    - name: Construir a aplicação com Maven
      command: mvn clean install -X
      args:
        chdir: /opt/techshop

    - name: Iniciar a aplicação
      command: java -jar /opt/techshop/target/techshop.jar
      args:
        chdir: /opt/techshop
