- name: Provisionar e configurar ambiente TechShop
  hosts: all
  become: yes
  tasks:
    - name: Instalar Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Load Docker image
      command: docker load -i /path/to/techshop.tar

    - name: Run Docker container
      docker_container:
        name: techshop
        image: techshop:latest
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
        volumes:
          - /opt/techshop:/data
