- name: Provisionar e configurar ambiente TechShop
  hosts: localhost
  become: yes
  tasks:
    - name: Instalar o Java JDK 21
      apt:
        name: openjdk-21-jdk
        state: present
      become: yes

    - name: Instalar Maven
      apt:
        name: maven
        state: present
      become: yes

    - name: Clonar o repositório da aplicação
      git:
        repo: 'https://github.com/1DanielMarques/techshop.git'
        dest: /opt/techshop
        version: master

    - name: Construir a aplicação com Maven
      command: mvn clean install
      args:
        chdir: /opt/techshop
      register: mvn_output
      ignore_errors: yes

    - name: Exibir log do Maven
      debug:
        msg: "{{ mvn_output.stdout }}"
      when: mvn_output.rc != 0

    - name: Iniciar a aplicação
      command: java -jar /opt/techshop/target/techshop.jar
      args:
        chdir: /opt/techshop
      when: mvn_output.rc == 0
