name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run unit tests
        run: mvn test

      - name: Run integration tests
        run: mvn verify

      - name: Build Docker image
        run: docker build -t techshop:latest .

      - name: Save Docker image
        run: docker save -o techshop.tar techshop:latest

      - name: Upload Docker image
        uses: actions/upload-artifact@v2
        with:
          name: techshop-image
          path: techshop.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker image
        uses: actions/download-artifact@v2
        with:
          name: techshop-image
          path: .

      - name: Ensure downloaded file is correct
        run: |
          echo "Listing contents of the current directory:"
          ls -alh
          echo "Verifying the downloaded file:"
          file techshop.tar
          echo "Checking if it is a regular file:"
          if [ -f techshop.tar ]; then echo "File exists and is a regular file"; else echo "File does not exist or is not a regular file"; exit 1; fi

      - name: Load Docker image
        run: docker load -i techshop.tar

      - name: Set up Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Configure Ansible inventory
        run: |
          mkdir -p ansible
          echo '[local]' > ansible/inventory.ini
          echo 'localhost ansible_connection=local' >> ansible/inventory.ini

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbooks/deploy_techshop.yml
